name: quantifier-recommender-env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - azure-ai-ml
      - azure-identity
      - mlflow
      - azureml-mlflow
      - cvxpy
      - joblib
      - matplotlib
      - mlquantify
      - numpy
      - pandas
      - pymfe
      - QuaPy
      - scikit-learn
      - seaborn
      - xgboost
